### ISSUE TITLE
Input file missing fields and truncated lines

### ISSUE THREAD

**Issue by tiagofilipe12** [ODiogoSilva/templates#1]
While trying some files with `abricate_processing.py`, I have found the following error:

```
Traceback (most recent call last):
  File "/home/***/templates/process_abricate.py", line 52, in __init__
    self.parse_files(fls)
  File "/home/***/templates/process_abricate.py", line 71, in parse_files
    self._parser(f)
  File "/home/***/templates/process_abricate.py", line 102, in _parser
    coverage = float(fields[8])
IndexError: list index out of range
```

This error happens because there is no field[8] and this is caused by the input file. Check this two lines:

```
master_fasta_full_plasmid_db_07202017_v5.fas    NC_001735_4_Enterobacter_aerogenes_plasmid_R751__complete_sequence      32820   33071   AAC(6')-Ib7     1-252/980       ====........... 0/0     25.71   99.21   card    Y11946.1:1-981
master_fasta_full_plasmid_db_07202017_v5.fas    NC_001735_4_Enterobacter_aerogenes_plasmid_R751__complete_sequence
        33006   33062   aadA9   845-901/901     ..............= 0/0     6.33    100.00  card    DQ390458:3096-3996
```
**Putative reason**
This seems to occur because there is a new line character (`\n`) within the intended line, and since the parser parses by line it reports that in that specific line the field[8] doesn't exist but in fact after `field[1]` there must be a line break.

Furthermore and linked to this `fields` issue I have found another case they may occur (this one easier to bypass but still annoying):

Error message:

```
Traceback (most recent call last):
  File "/home/***/templates/process_abricate.py", line 52, in __init__
    self.parse_files(fls)
  File "/home/***/templates/process_abricate.py", line 71, in parse_files
    self._parser(f)
  File "/home/***/templates/process_abricate.py", line 115, in _parser
    "accession": fields[11],
IndexError: list index out of range

```

And the line that gave raise to this error:

```
master_fasta_full_plasmid_db_07202017_v5.fas    NC_001378_1_Shigella_sonnei_plasmid_pKYM__complete_sequence     1092    1324    Col(BS512)_1    1-233/233       =============== 0/0     100.00  100.00  plasmidfinder   NC_010656
master_fasta_full_plasmid_db_07202017_v5.fas    NC_001378_1_Shigella_sonnei_plasmid_pKYM__complete_sequence     1396    1588    Col(BS512)_1__NC_010656_dupe    1-193/193       =============== 0/0     100.00  98.96   plasmidfinder 
```

**Putative reason**
As one can see, this error occurred because last entry (index 11) doesn't exist at all in the main output from `abricate`.

**Comment by ODiogoSilva** [comment]
Concerning the first issue, I was unable to replicate. The original abricate output with the card database does not seem to contain that badly formatted line. Perhaps it was later introduced or there was some corruption? The md5sum of that file should be:

`0d24c6993b863e83a18a4363b78f4af9`

We could surround the parsing code within a try/except block that catches `IndexError` and logs a warning while ignoring the bad lines. However, for the time being, I would prefer that the parser would crash in such cases so that we can assess if there is a problem with the abricate output or if there was some unintended corruption.

The second issue does seem to occur with some frequency, though. However, I'm not entirely sure if it is supposed to happen or not. From the Abricate github page, I got the notion that the only optional field was the last one (product), and that the accession should be always there. For now, a solution would be to catch `IndexError` exceptions when gathering the accession number and store 'None` when the field doesn't exist. However, I'll report this to abricate.

**Comment by tiagofilipe12** [comment]
Ok. Tks. I will check the md5sum later. 

**Update**

md5sum was in fact different, since I modified the header of the file, because of the repetition of the header itself...

So, I agree with you, it would be preferable if the original output file from abricate doesn't have the issue at all, instead of trying to fix it afterwards.
