### ISSUE TITLE
Implement unit tests for each template

### ISSUE THREAD

**Issue by tiagofilipe12** [ODiogoSilva/templates#2]
Each template should have its own set of unit tests, so that modifications can be smoothly done without breaking anything.

**Comment by ODiogoSilva** [comment]
There are several issues with including the unittests in this repository. First, they are usually pulled/clone with the remaining scripts, and they are not necessary outside this scope. Second, in the structure of this repository, it is not possible (without some convoluted hacks) to include these tests with a continuous integration service that provides automatic testing. Since the structure of the repository is important for its inclusion in assemblerflow (or other nextflow pipelines), we cannot go that way. I'll start with a couple of alternatives:

- Include the tests in the assemblerflow repository. Even though these templates are not an integral part of that repository, assemblerflow does depend on them do correctly function. 

- Create another repository dedicated to testing the templates. This repository could have the structure required for easy integration with CI services.

**Comment by tiagofilipe12** [comment]
Any of those is fine and maybe we can include in the README a link to the unittests (tests it self and results), similarly to what you have implemented for changelog and API documentation. Although I have my reservations on polluting assemblerflow repo with unit tests from templates (because it will become too confusing), I guess that would be the easiest way to check for issues on assemblerflow pipelines in PRs.
